import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";
import Link from "next/link";
import Header from "./components/Header";
import Hero from "./Hero";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />

        {children}
        <footer className="container py-8 text-center text-gray-500">
          Career Base &copy; 2025 - All rights reserved.
        </footer>
      </body>
    </html>
  );
}
